# 注释参数仅供示例使用, 此配置仅作模板使用，请勿在此文件直接更改，
name: FilterBwaSortDup
# 过滤Fq组件
filter:
  # 用分号;分隔, 支持批量文件输入，rg信息可选
  i:
    - fq: /data/lush-dev/shijiashuai/data/FastQ/fastq_1/CL100012105_L1_1_1_s1.fq.gz;/data/lush-dev/shijiashuai/data/FastQ/fastq_1/CL100012105_L1_1_2_s1.fq.gz
      rg: "@RG\\tID:id-1\\tSM:sm-1\\tLB:lib1\\tPL:MGI"
    - fq: /data/lush-dev/shijiashuai/data/FastQ/fastq_1/CL100012105_L1_1_1_s2.fq.gz;/data/lush-dev/shijiashuai/data/FastQ/fastq_1/CL100012105_L1_1_2_s2.fq.gz
      rg: "@RG\\tID:id-2\\tSM:sm-2\\tLB:lib2\\tPL:MGI"
    # - fq: /data/lush-dev/shijiashuai/data/FastQ/fastq_1/CL100012105_L1_1_1_s3.fq;/data/lush-dev/shijiashuai/data/FastQ/fastq_1/CL100012105_L1_1_2_s3.fq
    #   rg: "@RG\\tID:id-3\\tSM:sm-3\\tLB:lib3\\tPL:MGI"
    # - fq: /data/lush-dev/shijiashuai/data/FastQ/fastq_1/CL100012105_L1_1_1_s4.fq;/data/lush-dev/shijiashuai/data/FastQ/fastq_1/CL100012105_L1_1_2_s4.fq
    #   rg: "@RG\\tID:id-4\\tSM:sm-4\\tLB:lib4\\tPL:MGI"
    # - fq: /data/lush-dev/shijiashuai/data/FastQ/fastq_1/CL100012105_L1_1_1_s5.fq;/data/lush-dev/shijiashuai/data/FastQ/fastq_1/CL100012105_L1_1_2_s5.fq
    #   rg: "@RG\\tID:id-5\\tSM:sm-5\\tLB:lib5\\tPL:MGI"
  # 输出文件的路径
  o: /data/lush-dev/shijiashuai/workspace/out/lush_aligner/FilterBwaSortDup/results/20240711
  # bwa mem比对的线程数 [1] INT
  t: 10
  # fastq文件读取的批次大小,默认为50000
  batch_size: 100000
  adapter:
    - AGATCGGAAGAGCACACGTCTGAACT
    - AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
  # adapter's shortest match ratio(default: [0.5])
  # m: 0.8
  # the max mismatch number when match the adapter(default: [1])
  # b: 2
  # low quality threshold(default: [5])
  # l: 5
  # low quality rate(default: [0.5])
  # q: 0.5
  # mean quality threshold(default: [0])
  # w: 20
  # N rate threshold(default: [0.05])
  # n: 0.05
  # A rate threshold, 0 means not filter(default: [0])
  # a: 0.9
  # quality offset, for example: illumina18 is 33, 0 means infered by program(default: [0])
  # s: 33
  # 是否分目录保存结果，默认为true
  d: false
  # 截取fastQ文件总共的前n行，浮点数，单位 M(1024 * 1024). 默认为0, 表示不进行截取
  c: 0

# 比对组件
bwa:
  # 参考序列路径
  #index: /data/lush-dev/shijiashuai/data/index/hg19/hg19.fasta
  index: /data/pipelines/WGS_bgionline/db/GRCh38/ref/GRCh38_no_alt.fna
  v: 1
  # worker的数量 [1] INT
  worker_num: 3
  # 单个worker的比对的线程数 [1] INT
  t: 40

# 排序去重组件
sort_dup:
  # 输出文件路径：
  o: /data/lush-dev/shijiashuai/workspace/out/lush_aligner/FilterBwaSortDup/results/20240711/filterbwasortdup.sam
  # 线程数[必须 >= 32]
  t: 64
  # 临时文件路径，需要有读写权限
  z: /data/lush-dev/shijiashuai/workspace/out/lush_aligner/FilterBwaSortDup/results/20240711/tmp
  # bam切分模式：0不切分,1只切分unmap,2按照染色体切分 [默认值：0]
  segment_mode: 0


